# Generated by Django 5.2.3 on 2025-06-17 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("descricao", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Origem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("descricao", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Origem",
                "verbose_name_plural": "Origens",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="SubCategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategorias",
                        to="api.categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcategoria",
                "verbose_name_plural": "Subcategorias",
                "ordering": ["categoria__nome", "nome"],
                "unique_together": {("categoria", "nome")},
            },
        ),
        migrations.CreateModel(
            name="Lancamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_transacao", models.DateField(help_text="Data da transação")),
                (
                    "data_upload",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data do upload do OFX/criação do registro",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, help_text="Valor da transação", max_digits=10
                    ),
                ),
                (
                    "descricao_original",
                    models.CharField(
                        help_text="Descrição original do OFX ou entrada manual",
                        max_length=255,
                    ),
                ),
                (
                    "tipo_transacao",
                    models.CharField(
                        choices=[
                            ("DEBIT", "Débito"),
                            ("CREDIT", "Crédito"),
                            ("OTHER", "Outro"),
                        ],
                        help_text="Tipo de transação (Débito/Crédito)",
                        max_length=10,
                    ),
                ),
                (
                    "status_conciliacao",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente de Conciliação"),
                            ("conciliado", "Conciliado"),
                            ("ignorado", "Ignorado"),
                        ],
                        default="pendente",
                        help_text="Status da conciliação do lançamento",
                        max_length=10,
                    ),
                ),
                (
                    "referencia_mes",
                    models.CharField(
                        blank=True,
                        help_text="Mês de referência (AAAA-MM)",
                        max_length=7,
                        null=True,
                    ),
                ),
                (
                    "descricao_editada",
                    models.CharField(
                        blank=True,
                        help_text="Descrição editada pelo usuário",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "hash_transacao",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Hash para identificar transações duplicadas",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.categoria",
                    ),
                ),
                (
                    "origem",
                    models.ForeignKey(
                        blank=True,
                        help_text="Origem do lançamento (Banco, Cartão)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.origem",
                    ),
                ),
                (
                    "sub_categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.subcategoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lançamento",
                "verbose_name_plural": "Lançamentos",
                "ordering": ["-data_transacao", "-data_upload"],
            },
        ),
    ]
